---
version: '2'
services:
  smartstub:
    build: .
    ports:
      - '8080:8080'
      - '9090:9090'
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: smart-stub
      POSTGRES_USER: smart-stub
      POSTGRES_DB: smart-stub