---
  - name: install gcc
    apt: name=gcc state=latest update_cache=yes
    become: true

  - name: install libpcre3
    apt: name=libpcre3 state=latest
    become: true

  - name: install libpcre3-dev
    apt: name=libpcre3-dev state=latest
    become: true

  - name: install make
    apt: name=make state=latest
    become: true

  - name: install zlib-devel
    apt: name=zlib1g-dev state=latest
    become: true