  - name: add key for nginx repo
    apt_key:
       id: ABF5BD827BD9BF62
       keyserver: keyserver.ubuntu.com
    become: True    

  - name: add nginx official repo deb
    apt_repository:
       repo: deb http://nginx.org/packages/debian/ jessie nginx
       state: present
       update_cache: yes
    become: true

  - name: add nginx official src repo deb
    apt_repository:
       repo: deb-src http://nginx.org/packages/debian/ jessie nginx
       state: present
       update_cache: yes
    become: true

  - name: install nginx
    apt: name=nginx state=latest force=yes
    become: true
