---
  - name: modules src dir
    file: path=/tmp/ngx_modules state=directory

  - name: download modules
    get_url: 
      url: "{{ item.value.url }}"
      dest: "/tmp/ngx_modules/{{ item.value.name }}"
    with_dict: "{{ nginx_modules }}"


  - name: extract modules
    unarchive: 
      src: "/tmp/ngx_modules/{{ item.value.name }}"
      dest: /tmp/ngx_modules
      remote_src: yes
    with_dict: "{{ nginx_modules }}"

  - name: get nginx source
    get_url: url=http://nginx.org/download/nginx-1.12.0.tar.gz dest=/tmp/nginx-1.12.0.tar.gz

  - name: extract nginx
    unarchive: src=/tmp/nginx-1.12.0.tar.gz dest=/tmp remote_src=yes

  - name: compile modules
    debug:
      # var: sources
      msg:  |
       ./configure --with-compat \	
            {% for item in nginx_modules %}
               --add-dynamic-module="{{ item }}" \
            {% endfor %}      
