---
  - name: install openjdk 1.8
    yum:
      name: java-1.8.0-openjdk
      state: latest
      update_cache: yes
    become: yes

  - name: install openjdk 1.8 devel
    yum:
      name: java-1.8.0-openjdk-devel
      state: latest
      update_cache: yes
    become: yes

  - name: get java directory
    shell: dirname $(readlink $(readlink $(which java)))
    register: dir_name

  - name: configure env vars
    shell: |
        echo "export JAVA_HOME={{ item }}" >> /etc/profile
        echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile
        echo "CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar" >> /etc/profile
    become: yes
    with_items:
      - "{{ dir_name.stdout_lines }}"
