---
  - name: add key for openresty repository
    apt_key:
      url: https://openresty.org/package/pubkey.gpg
      state: present
    become: true

  - name: add openresty repository
    apt_repository:
      repo: deb http://openresty.org/package/debian jessie openresty
      state: present
      update_cache: yes
    become: true

  - name: install openresty
    apt:
      name: openresty
      state: latest
    become: yes

