---
  - name: Add openresty repository
    yum_repository:
      name: openresty repo
      baseurl: https://openresty.org/package/centos/openresty.repo
      gpgkey: https://openresty.org/package/pubkey.gpg
      state: present
    become: true

  - name: Install openresty
    yum:
      name: openresty
      state: latest
      update_cache: yes
    become: yes
