#!/bin/bash


PG_PS=pgsql
PG_SRV=postgresql-9.6
APP_PS=smart-stab
ENV_TOOLS=${CFGDIR}/envtools


if [[ $(ps auxw | grep ${PG_PS} | grep -v grep | wc -l) != 1 ]];
then
    ${ENV_TOOLS} startdb
    echo "Starting system ${PG_SRV} daemon"
fi

sleep 1;

if [[ $(ps auxw | grep ${APP_PS} | grep -v grep | wc -l) != 1 ]];
then
    echo "Starting smart-stab...."
    su java -jar ${APPDIR}/smart-stub.jar > /dev/null
fi