---
  - name: install common modules for ngix build
    package: name=gcc state=latest
    become: true

  - name: install libpcre3 for nginx
    package: name=libpcre3 state=latest
    become: true

  - name: install libpcre3-dev for nginx
    package: name=libpcre3-dev state=latest
    become: true

  - name: install make
    package: name=make state=latest
    become: true

  - name: Creates directory
    file: path=/tmp/luajit state=directory

  - name: Download luajit
    get_url: url=http://luajit.org/download/LuaJIT-2.0.5.tar.gz dest=/tmp/luajit/

  - name: unarchive luajit
    unarchive: src=/tmp/luajit/LuaJIT-2.0.5.tar.gz dest=/tmp/luajit/ remote_src=True

  - name: make luajit
    become: true
    shell: make && make install  
    args:
      chdir: /tmp/luajit/LuaJIT-2.0.5
